version: '3'

services:
  expo:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - 19006:19006
      - 19001:19001 
      - 19002:19002
    volumes:
      - .:/opt/expo_app/app:delegated
      - ./package.json:/opt/expo_app/package.json
      - ./package-lock.json:/opt/expo_app/package-lock.json
    networks:
      - nspm

networks:
  nspm:
    name: nspm
