version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - nspm

  mongodb:
    image: mongo:5.0.5
    volumes:
      - ./.docker/dbdata:/data/db
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=global
    networks:
      - nspm

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb
    networks:
      - nspm

networks:
  nspm:
    name: nspm
